# Generated by Django 2.2 on 2019-09-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190919_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='file',
            new_name='download',
        ),
    ]
