# Generated by Django 2.2 on 2019-09-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='teacher_name',
        ),
    ]
