# Generated by Django 2.2 on 2019-09-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190924_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher_name',
            new_name='teacher',
        ),
    ]
