# Generated by Django 2.2 on 2019-09-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_courseorg_is_classics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='is_classics',
        ),
    ]
